import localFont from "next/font/local";
import StoreProvider from "./StoreProvider";
import Header from "../components/Header";
import { useDispatch, useSelector } from "react-redux";
import { checkToken } from "../store/method/authMethod";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Appointment Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  ``;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
